### ISSUE TITLE
Branch displayed in update view is not the actual branch

### ISSUE THREAD

**Issue by vogti** [Chronos-EaaS/Chronos-Control#38]
The name of the current branch is taken from the config file and is not actually determined using the repo. This means, that when changing the branch in the file, the displayed branch is wrong until  someone triggers an update.

A nice solution would be to display both:
```
Current branch: 
After update: 
```

**Comment by s3inlc** [comment]
This issue was already fixed in the referenced pull request, therefore I close it.
